export const UniswapV4PositionManagerAbi = [
  {
    name: "increaseLiquidity",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "liquidity", type: "uint256" },
      { name: "amount0Max", type: "uint128" },
      { name: "amount1Max", type: "uint128" },
      { name: "hookData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "decreaseLiquidity",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "liquidity", type: "uint256" },
      { name: "amount0Min", type: "uint128" },
      { name: "amount1Min", type: "uint128" },
      { name: "hookData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "mintPosition",
    type: "function",
    stateMutability: "pure",
    inputs: [
      {
        name: "key",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          {
            name: "currency0",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "currency1",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "fee",
            type: "uint24",
            internalType: "uint24",
          },
          {
            name: "tickSpacing",
            type: "int24",
            internalType: "int24",
          },
          {
            name: "hooks",
            type: "address",
            internalType: "contract IHooks",
          },
        ],
      },
      { name: "tickLower", type: "int24" },
      { name: "tickUpper", type: "int24" },
      { name: "liquidity", type: "uint256" },
      { name: "amount0Max", type: "uint128" },
      { name: "amount1Max", type: "uint128" },
      { name: "owner", type: "address" },
      { name: "hookData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "burnPosition",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "amount0Min", type: "uint128" },
      { name: "amount1Min", type: "uint128" },
      { name: "hookData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "increaseLiquidityFromDeltas",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "amount0Max", type: "uint128" },
      { name: "amount1Max", type: "uint128" },
      { name: "hookData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "mintPositionFromDeltas",
    type: "function",
    stateMutability: "pure",
    inputs: [
      {
        name: "key",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          {
            name: "currency0",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "currency1",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "fee",
            type: "uint24",
            internalType: "uint24",
          },
          {
            name: "tickSpacing",
            type: "int24",
            internalType: "int24",
          },
          {
            name: "hooks",
            type: "address",
            internalType: "contract IHooks",
          },
        ],
      },
      { name: "tickLower", type: "int24" },
      { name: "tickUpper", type: "int24" },
      { name: "amount0Max", type: "uint128" },
      { name: "amount1Max", type: "uint128" },
      { name: "owner", type: "address" },
      { name: "hookData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "settle",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "currency", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "payerIsUser", type: "bool" },
    ],
    outputs: [],
  },
  {
    name: "settlePair",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "currency0", type: "address" },
      { name: "currency1", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "take",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "currency", type: "address" },
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "takePair",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "currency0", type: "address" },
      { name: "currency1", type: "address" },
      { name: "recipient", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "closeCurrency",
    type: "function",
    stateMutability: "pure",
    inputs: [{ name: "currency", type: "address" }],
    outputs: [],
  },
  {
    name: "clearOrTake",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "currency", type: "address" },
      { name: "amountMax", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "sweep",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "currency", type: "address" },
      { name: "to", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "wrap",
    type: "function",
    stateMutability: "pure",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    name: "unwrap",
    type: "function",
    stateMutability: "pure",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
] as const;
