import type { Address, Hex } from "viem";

/**
 * Core Action Types
 * Based on the Actions.sol contract from Licredity v1 Periphery
 */
export const ActionType = {
  DEPOSIT_FUNGIBLE: 0x00,
  DEPOSIT_NON_FUNGIBLE: 0x01,
  WITHDRAW_FUNGIBLE: 0x02,
  WITHDRAW_NON_FUNGIBLE: 0x03,
  INCREASE_DEBT_AMOUNT: 0x04,
  INCREASE_DEBT_SHARE: 0x05,
  DECREASE_DEBT_AMOUNT: 0x06,
  DECREASE_DEBT_SHARE: 0x07,
  SEIZE: 0x08,
  EXCHANGE: 0x09,
  SWITCH: 0x0a,
  UNISWAP_V4_POSITION_MANAGER_CALL: 0x0b,
  UNISWAP_V4_POOL_MANAGER_CALL: 0x0c,
  UNISWAP_V4_SWAP: 0x0d,
  UNISWAP_V4_TAKE: 0x0e,
  UNISWAP_V4_SETTLE: 0x0f,
  UNISWAP_V4_SWEEP: 0x10,
  DYN_CALL: 0x11,
} as const;
